'use client';

import { useState, useEffect, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useTheme } from '@/contexts/ThemeContext';
import { 
  StickyNote, 
  Plus, 
  X, 
  Edit, 
  Trash2, 
  Clock,
  AlertCircle,
  Lightbulb,
  Target,
  Image as ImageIcon,
  Smile,
  Palette,
  Sparkles,
  Star,
  Heart,
  Flame,
  Zap,
  Globe,
  Book,
  Calendar,
  CheckCircle,
  TrendingUp,
  DollarSign,
  Wallet,
  PiggyBank,
  CreditCard,
  Banknote,
  Coins,
  ArrowUpRight,
  ArrowDownRight,
  BarChart3,
  PieChart,
  LineChart
} from 'lucide-react';
import { cn } from '@/lib/utils';

export interface DashboardNote {
  id: string;
  content: string;
  color: 'yellow' | 'blue' | 'green' | 'red' | 'purple' | 'gradient-blue' | 'gradient-purple' | 'gradient-sunset' | 'pattern-dots' | 'pattern-grid';
  type: 'reminder' | 'idea' | 'goal' | 'alert' | 'general' | 'transaction' | 'budget' | 'financial-goal';
  customIcon?: string;
  theme: 'light' | 'dark' | 'auto';
  backgroundImage?: string;
  coverImage?: string;
  emoji?: string;
  createdAt: string;
  updatedAt: string;
  isPinned: boolean;
  isFavorite: boolean;
  linkedTransactionId?: string;
  linkedBudgetId?: string;
  linkedGoalId?: string;
  isAutoGenerated?: boolean;
}

const NOTE_COLORS = {
  yellow: 'bg-yellow-100 dark:bg-yellow-900/30 border-yellow-300 dark:border-yellow-700 text-yellow-900 dark:text-yellow-100',
  blue: 'bg-blue-100 dark:bg-blue-900/30 border-blue-300 dark:border-blue-700 text-blue-900 dark:text-blue-100',
  green: 'bg-green-100 dark:bg-green-900/30 border-green-300 dark:border-green-700 text-green-900 dark:text-green-100',
  red: 'bg-red-100 dark:bg-red-900/30 border-red-300 dark:border-red-700 text-red-900 dark:text-red-100',
  purple: 'bg-purple-100 dark:bg-purple-900/30 border-purple-300 dark:border-purple-700 text-purple-900 dark:text-purple-100',
  'gradient-blue': 'bg-gradient-to-br from-blue-100 to-cyan-100 dark:from-blue-900/40 dark:to-cyan-900/40 border-blue-300 dark:border-blue-700 text-blue-900 dark:text-blue-100',
  'gradient-purple': 'bg-gradient-to-br from-purple-100 to-pink-100 dark:from-purple-900/40 dark:to-pink-900/40 border-purple-300 dark:border-purple-700 text-purple-900 dark:text-purple-100',
  'gradient-sunset': 'bg-gradient-to-br from-orange-100 to-red-100 dark:from-orange-900/40 dark:to-red-900/40 border-orange-300 dark:border-orange-700 text-orange-900 dark:text-orange-100',
  'pattern-dots': 'bg-yellow-50 dark:bg-yellow-950/30 border-yellow-300 dark:border-yellow-700 text-yellow-900 dark:text-yellow-100 [background-image:radial-gradient(circle,currentColor_0.1_1px,transparent_1px)] dark:[background-image:radial-gradient(circle,rgba(255,255,255,0.05)_1px,transparent_1px)] [background-size:16px_16px]',
  'pattern-grid': 'bg-blue-50 dark:bg-blue-950/30 border-blue-300 dark:border-blue-700 text-blue-900 dark:text-blue-100 [background-image:linear-gradient(currentColor_0.1_1px,transparent_1px),linear-gradient(90deg,currentColor_0.1_1px,transparent_1px)] dark:[background-image:linear-gradient(rgba(255,255,255,0.05)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.05)_1px,transparent_1px)] [background-size:20px_20px]',
};

const CUSTOM_ICONS = [
  { name: 'Star', icon: Star, value: 'star' },
  { name: 'Heart', icon: Heart, value: 'heart' },
  { name: 'Flame', icon: Flame, value: 'flame' },
  { name: 'Zap', icon: Zap, value: 'zap' },
  { name: 'Globe', icon: Globe, value: 'globe' },
  { name: 'Book', icon: Book, value: 'book' },
  { name: 'Calendar', icon: Calendar, value: 'calendar' },
  { name: 'CheckCircle', icon: CheckCircle, value: 'check' },
  { name: 'TrendingUp', icon: TrendingUp, value: 'trending' },
  { name: 'DollarSign', icon: DollarSign, value: 'dollar' },
  { name: 'Wallet', icon: Wallet, value: 'wallet' },
  { name: 'PiggyBank', icon: PiggyBank, value: 'piggy' },
  { name: 'CreditCard', icon: CreditCard, value: 'card' },
  { name: 'Banknote', icon: Banknote, value: 'banknote' },
  { name: 'Coins', icon: Coins, value: 'coins' },
  { name: 'ArrowUpRight', icon: ArrowUpRight, value: 'up' },
  { name: 'ArrowDownRight', icon: ArrowDownRight, value: 'down' },
  { name: 'BarChart3', icon: BarChart3, value: 'bar' },
  { name: 'PieChart', icon: PieChart, value: 'pie' },
  { name: 'LineChart', icon: LineChart, value: 'line' },
];

const EMOJIS = [
  '📝', '💡', '🎯', '⚡', '🔥', '💰', '💳', '🏦', '💵', '📊',
  '📈', '📉', '💎', '🌟', '⭐', '❤️', '🚀', '🎉', '✅', '❌',
  '📅', '🕐', '🔔', '💭', '📌', '🎨', '🖼️', '📷', '🎵', '🎮',
  '🏠', '🚗', '✈️', '🛒', '🍕', '☕', '🍔', '🎁', '🎂', '🌈',
];

const NOTE_TYPES = [
  { value: 'general', icon: StickyNote, label: 'General' },
  { value: 'reminder', icon: Clock, label: 'Reminder' },
  { value: 'idea', icon: Lightbulb, label: 'Idea' },
  { value: 'goal', icon: Target, label: 'Goal' },
  { value: 'alert', icon: AlertCircle, label: 'Alert' },
  { value: 'transaction', icon: DollarSign, label: 'Transaction' },
  { value: 'budget', icon: Wallet, label: 'Budget' },
  { value: 'financial-goal', icon: TrendingUp, label: 'Financial Goal' },
];

interface DashboardNotesProps {
  className?: string;
  transactions?: Array<{ id: string; description: string; amount: number; category: string; date: string }>;
  budgets?: Array<{ id: string; category: string; budget: number; spent: number }>;
  goals?: Array<{ id: string; name: string; target: number; current: number }>;
  onLinkTransaction?: (noteId: string, transactionId: string) => void;
  onLinkBudget?: (noteId: string, budgetId: string) => void;
  onLinkGoal?: (noteId: string, goalId: string) => void;
}

export function DashboardNotes({ 
  className,
  transactions = [],
  budgets = [],
  goals = [],
  onLinkTransaction,
  onLinkBudget,
  onLinkGoal
}: DashboardNotesProps) {
  const { resolvedTheme } = useTheme();
  const [notes, setNotes] = useState<DashboardNote[]>([]);
  const [isAddingNote, setIsAddingNote] = useState(false);
  const [editingNote, setEditingNote] = useState<string | null>(null);
  const [newNoteContent, setNewNoteContent] = useState('');
  const [selectedColor, setSelectedColor] = useState<keyof typeof NOTE_COLORS>('yellow');
  const [selectedType, setSelectedType] = useState<DashboardNote['type']>('general');
  const [showEmojiPicker, setShowEmojiPicker] = useState(false);
  const [showIconPicker, setShowIconPicker] = useState(false);
  const [showAdvancedOptions, setShowAdvancedOptions] = useState(false);
  const [selectedEmoji, setSelectedEmoji] = useState('');
  const [selectedCustomIcon, setSelectedCustomIcon] = useState('');
  const [selectedBackgroundImage, setSelectedBackgroundImage] = useState('');
  const [selectedTheme, setSelectedTheme] = useState<'light' | 'dark' | 'auto'>('auto');
  const [showLinkingOptions, setShowLinkingOptions] = useState(false);
  const [selectedTransactionId, setSelectedTransactionId] = useState('');
  const [selectedBudgetId, setSelectedBudgetId] = useState('');
  const [selectedGoalId, setSelectedGoalId] = useState('');

  // Load notes from localStorage
  useEffect(() => {
    const savedNotes = localStorage.getItem('dashboard-notes');
    if (savedNotes) {
      try {
        setNotes(JSON.parse(savedNotes));
      } catch (error) {
        console.warn('Failed to load dashboard notes:', error);
      }
    }
  }, []);

  // Save notes to localStorage
  useEffect(() => {
    localStorage.setItem('dashboard-notes', JSON.stringify(notes));
  }, [notes]);

  const addNote = useCallback(() => {
    if (!newNoteContent.trim()) return;

    const newNote: DashboardNote = {
      id: `note-${Date.now()}`,
      content: newNoteContent,
      color: selectedColor,
      type: selectedType,
      customIcon: selectedCustomIcon || undefined,
      theme: selectedTheme,
      backgroundImage: selectedBackgroundImage || undefined,
      coverImage: undefined,
      emoji: selectedEmoji || undefined,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      isPinned: false,
      isFavorite: false,
      linkedTransactionId: selectedTransactionId || undefined,
      linkedBudgetId: selectedBudgetId || undefined,
      linkedGoalId: selectedGoalId || undefined,
      isAutoGenerated: false,
    };

    setNotes(prev => [newNote, ...prev]);
    setNewNoteContent('');
    setIsAddingNote(false);
    setSelectedColor('yellow');
    setSelectedType('general');
    setSelectedEmoji('');
    setSelectedCustomIcon('');
    setSelectedBackgroundImage('');
    setSelectedTheme('auto');
    setShowAdvancedOptions(false);
    setShowLinkingOptions(false);
    setShowEmojiPicker(false);
    setSelectedTransactionId('');
    setSelectedBudgetId('');
    setSelectedGoalId('');
  }, [newNoteContent, selectedColor, selectedType, selectedEmoji, selectedCustomIcon, selectedBackgroundImage, selectedTheme, selectedTransactionId, selectedBudgetId, selectedGoalId]);

  const updateNote = useCallback((noteId: string, content: string) => {
    setNotes(prev => prev.map(note => 
      note.id === noteId 
        ? { ...note, content, updatedAt: new Date().toISOString() }
        : note
    ));
    setEditingNote(null);
  }, []);

  const deleteNote = useCallback((noteId: string) => {
    setNotes(prev => prev.filter(note => note.id !== noteId));
  }, []);

  const togglePin = useCallback((noteId: string) => {
    setNotes(prev => prev.map(note => 
      note.id === noteId 
        ? { ...note, isPinned: !note.isPinned }
        : note
    ));
  }, []);

  const toggleFavorite = useCallback((noteId: string) => {
    setNotes(prev => prev.map(note => 
      note.id === noteId 
        ? { ...note, isFavorite: !note.isFavorite }
        : note
    ));
  }, []);

  const sortedNotes = [...notes].sort((a, b) => {
    // Pinned notes first
    if (a.isPinned && !b.isPinned) return -1;
    if (!a.isPinned && b.isPinned) return 1;
    
    // Favorite notes second
    if (a.isFavorite && !b.isFavorite) return -1;
    if (!a.isFavorite && b.isFavorite) return 1;
    
    // Then by update date
    return new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime();
  });

  const getNoteTypeIcon = (type: DashboardNote['type']) => {
    const noteType = NOTE_TYPES.find(t => t.value === type);
    return noteType ? noteType.icon : StickyNote;
  };

  const getCustomIcon = (iconName?: string) => {
    if (!iconName) return null;
    const customIcon = CUSTOM_ICONS.find(i => i.value === iconName);
    return customIcon ? customIcon.icon : null;
  };

  const getNoteTheme = (note: DashboardNote) => {
    if (note.theme === 'light') return 'light';
    if (note.theme === 'dark') return 'dark';
    return resolvedTheme || 'light';
  };

  // Smart suggestions based on financial context
  const getSmartSuggestions = useCallback(() => {
    const suggestions: Array<{ text: string; type: DashboardNote['type'] }> = [];

    // Budget alerts
    budgets.forEach(budget => {
      const percentage = (budget.spent / budget.budget) * 100;
      if (percentage >= 90 && percentage < 100) {
        suggestions.push({
          text: `${budget.category} budget is ${percentage.toFixed(0)}% used. Consider reducing spending.`,
          type: 'alert'
        });
      } else if (percentage >= 100) {
        suggestions.push({
          text: `${budget.category} budget exceeded by $${(budget.spent - budget.budget).toFixed(2)}. Review spending immediately.`,
          type: 'alert'
        });
      }
    });

    // Goal progress
    goals.forEach(goal => {
      const percentage = (goal.current / goal.target) * 100;
      if (percentage >= 50 && percentage < 75) {
        suggestions.push({
          text: `${goal.name} goal is ${percentage.toFixed(0)}% complete. Keep it up!`,
          type: 'financial-goal'
        });
      } else if (percentage >= 75 && percentage < 100) {
        suggestions.push({
          text: `${goal.name} goal is ${percentage.toFixed(0)}% complete. Almost there!`,
          type: 'financial-goal'
        });
      } else if (percentage >= 100) {
        suggestions.push({
          text: `🎉 ${goal.name} goal achieved! Time to set a new target.`,
          type: 'financial-goal'
        });
      }
    });

    // Large transactions
    transactions.slice(0, 5).forEach(transaction => {
      if (transaction.amount > 500) {
        suggestions.push({
          text: `Large expense: ${transaction.description} - $${transaction.amount.toFixed(2)}. Review if necessary.`,
          type: 'transaction'
        });
      }
    });

    return suggestions.slice(0, 5);
  }, [budgets, goals, transactions]);

  const smartSuggestions = getSmartSuggestions();

  // Auto-generate notes for budget alerts
  const generateAutoNotes = useCallback(() => {
    const autoNotes: DashboardNote[] = [];

    budgets.forEach(budget => {
      const percentage = (budget.spent / budget.budget) * 100;
      if (percentage >= 90) {
        autoNotes.push({
          id: `auto-budget-${budget.id}-${Date.now()}`,
          content: percentage >= 100 
            ? `⚠️ ${budget.category} budget exceeded! Spent: $${budget.spent.toFixed(2)} / Budget: $${budget.budget.toFixed(2)}`
            : `⚡ ${budget.category} budget warning: ${percentage.toFixed(0)}% used`,
          color: percentage >= 100 ? 'red' : 'yellow',
          type: 'budget',
          theme: 'auto',
          emoji: percentage >= 100 ? '🚨' : '⚡',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          isPinned: true,
          isFavorite: false,
          linkedBudgetId: budget.id,
          isAutoGenerated: true,
        });
      }
    });

    return autoNotes;
  }, [budgets]);

  return (
    <Card className={cn("rounded-lg", className)}>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <StickyNote className="h-5 w-5" />
            Dashboard Notes
          </CardTitle>
          <div className="flex gap-2">
            {smartSuggestions.length > 0 && (
              <Button
                size="sm"
                variant="outline"
                onClick={() => {
                  const suggestion = smartSuggestions[0];
                  setNewNoteContent(suggestion.text);
                  setSelectedType(suggestion.type);
                  setIsAddingNote(true);
                }}
                className="text-xs"
              >
                <Sparkles className="h-3 w-3 mr-1" />
                Smart Suggestion
              </Button>
            )}
            <Button
              size="sm"
              onClick={() => {
                const autoNotes = generateAutoNotes();
                if (autoNotes.length > 0) {
                  setNotes(prev => [...autoNotes, ...prev]);
                }
              }}
              variant="outline"
              className="text-xs"
            >
              <Zap className="h-3 w-3 mr-1" />
              Auto-Generate
            </Button>
            <Button
              size="sm"
              onClick={() => setIsAddingNote(true)}
              className="gap-2"
            >
              <Plus className="h-4 w-4" />
              Add Note
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {/* Add Note Form */}
        {isAddingNote && (
          <div className="mb-4 p-4 border rounded-lg space-y-3 bg-muted/50 dark:bg-muted/30 border-border dark:border-border/50">
            <textarea
              placeholder="Write your note here..."
              value={newNoteContent}
              onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setNewNoteContent(e.target.value)}
              className="min-h-[80px] w-full p-2 rounded-md border border-input bg-background text-sm placeholder:text-muted-foreground dark:placeholder:text-muted-foreground/70 focus:ring-2 focus:ring-primary"
              autoFocus
            />
            
            <div className="flex flex-wrap gap-2">
              {/* Color/Theme Selection */}
              <div className="flex gap-1 items-center">
                <Palette className="h-4 w-4 text-muted-foreground mr-1" />
                {(Object.keys(NOTE_COLORS) as Array<keyof typeof NOTE_COLORS>).map((color) => (
                  <button
                    key={color}
                    onClick={() => setSelectedColor(color)}
                    className={cn(
                      "w-6 h-6 rounded border-2 transition-all hover:scale-110",
                      NOTE_COLORS[color],
                      selectedColor === color ? 'ring-2 ring-offset-2 ring-primary dark:ring-offset-background' : 'opacity-60 hover:opacity-100'
                    )}
                    title={color}
                  />
                ))}
              </div>
              
              {/* Note Type Selection */}
              <div className="flex gap-1 items-center">
                {NOTE_TYPES.map((type) => {
                  const Icon = type.icon;
                  return (
                    <button
                      key={type.value}
                      onClick={() => setSelectedType(type.value as DashboardNote['type'])}
                      className={cn(
                        "px-2 py-1 rounded text-xs flex items-center gap-1 transition-all hover:scale-105",
                        selectedType === type.value 
                          ? 'bg-primary text-primary-foreground' 
                          : 'bg-muted hover:bg-muted/80 dark:hover:bg-muted/60'
                      )}
                    >
                      <Icon className="h-3 w-3" />
                      {type.label}
                    </button>
                  );
                })}
              </div>

              {/* Emoji Picker */}
              <div className="relative">
                <button
                  onClick={() => setShowEmojiPicker(!showEmojiPicker)}
                  className={cn(
                    "px-2 py-1 rounded text-xs flex items-center gap-1 transition-all hover:scale-105",
                    selectedEmoji ? 'bg-primary text-primary-foreground' : 'bg-muted hover:bg-muted/80 dark:hover:bg-muted/60'
                  )}
                >
                  <Smile className="h-3 w-3" />
                  {selectedEmoji || 'Emoji'}
                </button>
                {showEmojiPicker && (
                  <div className="absolute top-full left-0 mt-1 p-2 bg-background border border-border dark:border-border/50 rounded-lg shadow-lg z-10">
                    <div className="grid grid-cols-10 gap-1">
                      {EMOJIS.map((emoji) => (
                        <button
                          key={emoji}
                          onClick={() => {
                            setSelectedEmoji(emoji);
                            setShowEmojiPicker(false);
                          }}
                          className="text-lg hover:bg-muted dark:hover:bg-muted/50 rounded p-1 transition-all"
                        >
                          {emoji}
                        </button>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Advanced Options Toggle */}
              <button
                onClick={() => setShowAdvancedOptions(!showAdvancedOptions)}
                className={cn(
                  "px-2 py-1 rounded text-xs flex items-center gap-1 transition-all hover:scale-105",
                  showAdvancedOptions ? 'bg-primary text-primary-foreground' : 'bg-muted hover:bg-muted/80 dark:hover:bg-muted/60'
                )}
              >
                <Sparkles className="h-3 w-3" />
                Advanced
              </button>
            </div>

            {/* Advanced Options */}
            {showAdvancedOptions && (
              <div className="space-y-3 p-3 bg-background dark:bg-card border border-border dark:border-border/50 rounded-lg">
                {/* Custom Icon Selection */}
                <div>
                  <label className="text-xs font-medium mb-2 block">Custom Icon</label>
                  <div className="flex flex-wrap gap-1">
                    <button
                      onClick={() => setSelectedCustomIcon('')}
                      className={cn(
                        "px-2 py-1 rounded text-xs transition-all hover:scale-105",
                        !selectedCustomIcon ? 'bg-primary text-primary-foreground' : 'bg-muted hover:bg-muted/80 dark:hover:bg-muted/60'
                      )}
                    >
                      None
                    </button>
                    {CUSTOM_ICONS.map((icon) => {
                      const Icon = icon.icon;
                      return (
                        <button
                          key={icon.value}
                          onClick={() => setSelectedCustomIcon(icon.value)}
                          className={cn(
                            "px-2 py-1 rounded text-xs flex items-center gap-1 transition-all hover:scale-105",
                            selectedCustomIcon === icon.value 
                              ? 'bg-primary text-primary-foreground' 
                              : 'bg-muted hover:bg-muted/80 dark:hover:bg-muted/60'
                          )}
                        >
                          <Icon className="h-3 w-3" />
                        </button>
                      );
                    })}
                  </div>
                </div>

                {/* Theme Selection */}
                <div>
                  <label className="text-xs font-medium mb-2 block">Theme</label>
                  <div className="flex gap-1">
                    {(['auto', 'light', 'dark'] as const).map((theme) => (
                      <button
                        key={theme}
                        onClick={() => setSelectedTheme(theme)}
                        className={cn(
                          "px-2 py-1 rounded text-xs capitalize transition-all",
                          selectedTheme === theme 
                            ? 'bg-primary text-primary-foreground' 
                            : 'bg-muted hover:bg-muted/80'
                        )}
                      >
                        {theme}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Background Image URL */}
                <div>
                  <label className="text-xs font-medium mb-2 block">Background Image URL</label>
                  <input
                    type="text"
                    placeholder="https://example.com/image.jpg"
                    value={selectedBackgroundImage}
                    onChange={(e) => setSelectedBackgroundImage(e.target.value)}
                    className="w-full px-2 py-1 text-sm rounded-md border border-input bg-background text-muted-foreground placeholder:text-muted-foreground/70 focus:ring-2 focus:ring-primary"
                  />
                </div>

                {/* Financial Data Linking */}
                <div>
                  <label className="text-xs font-medium mb-2 block">Link to Financial Data</label>
                  <div className="space-y-2">
                    {/* Transaction Link */}
                    {transactions.length > 0 && (
                      <div>
                        <label className="text-xs text-muted-foreground mb-1 block">Transaction</label>
                        <select
                          value={selectedTransactionId}
                          onChange={(e) => setSelectedTransactionId(e.target.value)}
                          className="w-full px-2 py-1 text-sm rounded-md border border-input bg-background text-muted-foreground focus:ring-2 focus:ring-primary"
                        >
                          <option key="placeholder-transaction" value="">Select transaction...</option>
                          {transactions.map((t) => (
                            <option key={t.id} value={t.id}>
                              {t.description} - ${t.amount.toFixed(2)}
                            </option>
                          ))}
                        </select>
                      </div>
                    )}

                    {/* Budget Link */}
                    {budgets.length > 0 && (
                      <div>
                        <label className="text-xs text-muted-foreground mb-1 block">Budget</label>
                        <select
                          value={selectedBudgetId}
                          onChange={(e) => setSelectedBudgetId(e.target.value)}
                          className="w-full px-2 py-1 text-sm rounded-md border border-input bg-background text-muted-foreground focus:ring-2 focus:ring-primary"
                        >
                          <option key="placeholder-budget" value="">Select budget...</option>
                          {budgets.map((b) => (
                            <option key={b.id} value={b.id}>
                              {b.category} - ${b.spent.toFixed(2)} / ${b.budget.toFixed(2)}
                            </option>
                          ))}
                        </select>
                      </div>
                    )}

                    {/* Goal Link */}
                    {goals.length > 0 && (
                      <div>
                        <label className="text-xs text-muted-foreground mb-1 block">Financial Goal</label>
                        <select
                          value={selectedGoalId}
                          onChange={(e) => setSelectedGoalId(e.target.value)}
                          className="w-full px-2 py-1 text-sm rounded-md border border-input bg-background text-muted-foreground focus:ring-2 focus:ring-primary"
                        >
                          <option key="placeholder-goal" value="">Select goal...</option>
                          {goals.map((g) => (
                            <option key={g.id} value={g.id}>
                              {g.name} - ${g.current.toFixed(2)} / ${g.target.toFixed(2)}
                            </option>
                          ))}
                        </select>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            )}
            
            <div className="flex gap-2">
              <Button size="sm" onClick={addNote} disabled={!newNoteContent.trim()}>
                Save Note
              </Button>
              <Button size="sm" variant="outline" onClick={() => {
                setIsAddingNote(false);
                setNewNoteContent('');
                setSelectedColor('yellow');
                setSelectedType('general');
                setSelectedEmoji('');
                setSelectedCustomIcon('');
                setSelectedBackgroundImage('');
                setSelectedTheme('auto');
                setShowAdvancedOptions(false);
                setShowEmojiPicker(false);
                setShowLinkingOptions(false);
                setSelectedTransactionId('');
                setSelectedBudgetId('');
                setSelectedGoalId('');
              }}>
                Cancel
              </Button>
            </div>
          </div>
        )}

        {/* Notes Grid */}
        {sortedNotes.length === 0 && !isAddingNote ? (
          <div className="text-center py-8 text-muted-foreground dark:text-muted-foreground/80">
            <StickyNote className="h-12 w-12 mx-auto mb-3 opacity-50 dark:opacity-40" />
            <p className="dark:text-muted-foreground/80">No notes yet. Add your first note to get started!</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {sortedNotes.map((note) => {
              const NoteTypeIcon = getNoteTypeIcon(note.type);
              const CustomIconComponent = getCustomIcon(note.customIcon);
              const noteTheme = getNoteTheme(note);
              const isEditing = editingNote === note.id;
              
              return (
                <div
                  key={note.id}
                  className={cn(
                    "relative p-4 rounded-lg border-2 transition-all hover:shadow-lg hover:scale-[1.02] overflow-hidden",
                    NOTE_COLORS[note.color],
                    note.isPinned && 'ring-2 ring-primary ring-offset-2',
                    noteTheme === 'dark' && 'dark:bg-opacity-90',
                    note.backgroundImage && 'bg-cover bg-center bg-no-repeat'
                  )}
                  style={note.backgroundImage ? { backgroundImage: `url(${note.backgroundImage})` } : undefined}
                >
                  {/* Background overlay for readability */}
                  {note.backgroundImage && (
                    <div className="absolute inset-0 bg-white/80 dark:bg-black/70" />
                  )}
                  
                  {/* Note Header */}
                  <div className="relative flex items-start justify-between mb-2">
                    <div className="flex items-center gap-2">
                      {note.emoji && (
                        <span className="text-xl">{note.emoji}</span>
                      )}
                      {CustomIconComponent ? (
                        <CustomIconComponent className="h-4 w-4 opacity-70" />
                      ) : (
                        <NoteTypeIcon className="h-4 w-4 opacity-70" />
                      )}
                      <Badge variant="outline" className="text-xs bg-white/60 dark:bg-black/40 backdrop-blur-sm border-black/10 dark:border-white/10">
                        {NOTE_TYPES.find(t => t.value === note.type)?.label}
                      </Badge>
                    </div>
                    <div className="flex gap-1">
                      <button
                        onClick={() => toggleFavorite(note.id)}
                        className={cn(
                          "p-1 rounded transition-all",
                          note.isFavorite ? 'text-yellow-500' : 'text-muted-foreground hover:text-yellow-500'
                        )}
                      >
                        <Star className={cn("h-3 w-3", note.isFavorite && "fill-current")} />
                      </button>
                      <button
                        onClick={() => togglePin(note.id)}
                        className={cn(
                          "p-1 rounded transition-all",
                          note.isPinned ? 'text-primary' : 'text-muted-foreground hover:text-primary'
                        )}
                      >
                        <Clock className="h-3 w-3" />
                      </button>
                      <button
                        onClick={() => setEditingNote(note.id)}
                        className="p-1 rounded text-muted-foreground hover:text-primary transition-all"
                      >
                        <Edit className="h-3 w-3" />
                      </button>
                      <button
                        onClick={() => deleteNote(note.id)}
                        className="p-1 rounded text-muted-foreground hover:text-destructive transition-all"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                    </div>
                  </div>

                  {/* Note Content */}
                  {isEditing ? (
                    <div className="relative space-y-2">
                      <textarea
                        value={note.content}
                        onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => updateNote(note.id, e.target.value)}
                        className="min-h-[60px] w-full text-sm p-2 rounded-md border border-input bg-background placeholder:text-muted-foreground dark:placeholder:text-muted-foreground/70 focus:ring-2 focus:ring-primary"
                        autoFocus
                      />
                      <div className="flex gap-2">
                        <Button size="sm" onClick={() => setEditingNote(null)}>
                          Done
                        </Button>
                      </div>
                    </div>
                  ) : (
                    <p className="relative text-sm whitespace-pre-wrap break-words">{note.content}</p>
                  )}

                  {/* Note Footer */}
                  <div className="relative mt-2 pt-2 border-t border-black/10 dark:border-white/10">
                    <div className="flex items-center justify-between">
                      <p className="text-xs opacity-60 dark:opacity-70">
                        {new Date(note.updatedAt).toLocaleDateString()}
                      </p>
                      <div className="flex gap-1">
                        {note.linkedTransactionId && (
                          <Badge variant="outline" className="text-xs bg-blue-100 dark:bg-blue-900/40 backdrop-blur-sm border-blue-300 dark:border-blue-700 text-blue-900 dark:text-blue-100">
                            <DollarSign className="h-2 w-2 mr-1" />
                            Transaction
                          </Badge>
                        )}
                        {note.linkedBudgetId && (
                          <Badge variant="outline" className="text-xs bg-green-100 dark:bg-green-900/40 backdrop-blur-sm border-green-300 dark:border-green-700 text-green-900 dark:text-green-100">
                            <Wallet className="h-2 w-2 mr-1" />
                            Budget
                          </Badge>
                        )}
                        {note.linkedGoalId && (
                          <Badge variant="outline" className="text-xs bg-purple-100 dark:bg-purple-900/40 backdrop-blur-sm border-purple-300 dark:border-purple-700 text-purple-900 dark:text-purple-100">
                            <Target className="h-2 w-2 mr-1" />
                            Goal
                          </Badge>
                        )}
                        {note.isAutoGenerated && (
                          <Badge variant="secondary" className="text-xs bg-yellow-100 dark:bg-yellow-900/40 backdrop-blur-sm border-yellow-300 dark:border-yellow-700 text-yellow-900 dark:text-yellow-100">
                            <Zap className="h-2 w-2 mr-1" />
                            Auto
                          </Badge>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
